spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  data:
    redis:
      port: 6379
      host: localhost

    kafka:
      port: 9092
      host: localhost
      path: localhost:9092
      topics:
        default-partition: 1
        default-replication: 1
        topic-settings:
          match-end:
            name: match-end
          match-start:
            name: match-start
          lobby-start:
            name: lobby-start
          round-end:
            name: round-end

management:
  endpoints:
    web:
      exposure:
        include: health, info
  health:
    defaults:
      enabled: true
    show-details: always
    show-components: always

logging:
  level:
    root: info
    org.apache.kafka: OFF

auto:
  offset:
    reset: latest

#services:
#  s3:
#    endpoint: http://127.0.0.1:9000/
#    accessKey: user
#    secretKey: password
#

