spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  data:
    kafka:
      port: 9092
      host: 5.34.209.144
      path: 5.34.209.144:9092
      topics:
        default-partition: 1
        default-replication: 1
        topic-settings:
          match-end:
            name: match-end
          lobby-start:
            name: lobby-start

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
management:
  endpoints:
    web:
      exposure:
        include: health, info
  health:
    defaults:
      enabled: true
    show-details: always
    show-components: always

#services:
#  s3:
#    endpoint: http://127.0.0.1:9000/
#    accessKey: user
#    secretKey: password