spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
  data:
    redis:
      port: 6379
      host: localhost

    kafka:
      port: 9092
      host: localhost
      path: localhost:9092
      topics:
        default-partition: 1
        default-replication: 1
        topic-settings:
          match:
            name: match
          player:
            name: player
          lobby:
            name: lobby



#services:
#  s3:
#    endpoint: http://127.0.0.1:9000/
#    accessKey: user
#    secretKey: password
#

