spring:

  application:
    name: analytics-service

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5435/analyticsdb
    username: analyticsdb
    password: password

  data:
    kafka:
      group-id: analytics-group
      path: localhost:9092

  elasticsearch:
    uris: http://localhost:9200
    connection-timeout: 5s
    socket-timeout: 30s


async.settings:
  kafka:
    corePoolSize: 5
    maxPoolSize: 10
    queueCapacity: 100
