spring:
  application:
    name: tournament-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5434/tournamentdb
    username: tournamentdb
    password: password
  data:
    kafka:
      group-id: tournament-group
      path: localhost:9092

