spring:
  application:
    name: user-service
  data:
    redis:
      cache:
        default-ttl: 86400
        cache-settings:
          refresh-token:
            name: refresh-token
            ttl: ${jwt.tokens.refresh.expiration}
          blacklisted-token:
            name: blacklisted-token
            ttl: ${jwt.tokens.access.expiration}

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://5.34.209.144:5432/usersdb
    username: usersdb
    password: password

steam:
  api:
    token: ECD36B5DF3DFA8065A21C3B09F63881B
    url: https://api.steampowered.com
faceit:
  api:
    key: 428f358b-0e67-45a7-b339-41958254d3c1
jwt:
  tokens:
    access:
      key: 53A73E5F1C4E0A2D3B5F2D784E6A1B423D6F247D1F6E5C3A596D635A75327855
      expiration: 100000
    refresh:
      key: 53A73E5F1C4E0A2D3B5F2D784E6A1B423D6F247D1F6E5C3A596D635A75327855
      # expiration: 86400000
      expiration: 200000
