spring:

  application:
    name: matchmaking-service

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/matchmakingdb
    username: matchmakingdb
    password: password

  data:
    redis:
      lock-registry:
        lobby-lock-key: LOBBY_LOCK_KEY
        release-time-duration-millis: 10000

    kafka:
      group-id: matchmaking-group
      path: localhost:9092

dathost:
  username: "cadoni827@gmail.com"
  password: "smolensk863"
  servers-url: https://dathost.net/api/0.1/game-servers
  matches-url: https://dathost.net/api/0.1/cs2-matches

cors:
  allowed-origins:
    local: "http://127.0.0.1:5500"
    rodya: "http://localhost:4200"

async.settings:
  kafka:
    corePoolSize: 5
    maxPoolSize: 10
    queueCapacity: 100
  redis:
    settings:
      lobby:
        corePoolSize: 5
        maxPoolSize: 10
        queueCapacity: 100
