spring:
  application:
    name: matchmaking-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/matchmakingdb
    username: matchmakingdb
    password: password
  data:
    kafka:
      group-id: matchmaking-group

dathost:
  username: "cadoni827@gmail.com"
  password: "smolensk863"
  servers-url: https://dathost.net/api/0.1/game-servers
  matches-url: https://dathost.net/api/0.1/cs2-matches

cors:
  allowed-origins:
    local: "http://127.0.0.1:5500"
    rodya: "http://localhost:4200"


